In [2]:
import numpy as np

### 3變數

In [42]:
A1 = np.random.randint(-5, 5, size=(3, 3)) #從-5到5產生3X3矩陣
b1 = np.random.randint(-5, 5, size=(3, 1)) #從-5到5產生3X1矩陣

In [43]:
x1 = np.linalg.solve(A1, b1) #解方程式

In [44]:
print('A1={}\nb1={}\nx1={}'.format(A1, b1, x1)) #顯示結果

A1=[[-1 -1  2]
 [ 4  1  4]
 [ 1 -2 -1]]
b1=[[-2]
 [ 4]
 [ 0]]
x1=[[ 1.03030303]
 [ 0.60606061]
 [-0.18181818]]


### 驗算

In [46]:
np.matmul(A1, x1) #矩陣乘法

array([[-2.00000000e+00],
       [ 4.00000000e+00],
       [-2.77555756e-17]])

### 5變數

In [47]:
A2 = np.random.randint(-5, 5, size=(5, 5)) #從-5到5產生3X3矩陣
b2 = np.random.randint(-5, 5, size=(5, 1)) #從-5到5產生3X1矩陣

In [48]:
x2 = np.linalg.solve(A2, b2) #解方程式

In [49]:
print('A2={}\nb2={}\nx2={}'.format(A2, b2, x2)) #顯示結果

A2=[[ 0  1 -3 -1 -4]
 [-4 -5 -5 -2  0]
 [ 1  0  2 -4 -3]
 [ 1 -5 -5  3  4]
 [ 2  2 -3  1  2]]
b2=[[-4]
 [-4]
 [ 0]
 [ 3]
 [ 4]]
x2=[[ 1.05754885]
 [ 0.14351687]
 [ 0.04120782]
 [-0.57690941]
 [ 1.14920071]]


### 驗算

In [50]:
np.matmul(A2, x2) #矩陣乘法

array([[-4.],
       [-4.],
       [ 0.],
       [ 3.],
       [ 4.]])

### 10變數

In [51]:
A3 = np.random.randint(-5, 5, size=(10, 10)) #從-5到5產生3X3矩陣
b3 = np.random.randint(-5, 5, size=(10, 1)) #從-5到5產生3X1矩陣

In [52]:
x3 = np.linalg.solve(A3, b3) #解方程式

In [53]:
print('A3={}\nb3={}\nx3={}'.format(A3, b3, x3)) #顯示結果

A3=[[ 4  3  0  2 -5 -4 -3  4 -3 -2]
 [ 2  3  3 -4  2 -1 -1 -4  0 -5]
 [-2  0 -5 -1 -2  0 -1  1  4 -1]
 [-4 -2  0 -2  3  0 -4  4 -2  4]
 [ 4  1 -5  1  3  1  3 -2  4 -4]
 [-1 -5  0  0  1 -4  1 -4  4  1]
 [-1 -2 -2 -1  1 -1  4  3 -3 -3]
 [-3 -2  4 -1 -3  0  4 -3  3  4]
 [ 1 -1 -5  0 -5 -1  0 -1  2 -3]
 [ 0 -1 -5  4  4 -1 -1 -3 -5  0]]
b3=[[-2]
 [-3]
 [-1]
 [-5]
 [ 0]
 [ 2]
 [-3]
 [-2]
 [-2]
 [-1]]
x3=[[-1.59189505]
 [-1.09085639]
 [ 1.85547315]
 [ 3.47227886]
 [ 0.19501521]
 [ 1.18722696]
 [-1.03462384]
 [ 0.41852583]
 [ 1.21489726]
 [-2.64314625]]


### 驗算

In [54]:
np.matmul(A3, x3) #矩陣乘法

array([[-2.],
       [-3.],
       [-1.],
       [-5.],
       [ 0.],
       [ 2.],
       [-3.],
       [-2.],
       [-2.],
       [-1.]])